-- case statement

CREATE DATABASE PRACTICE;
USE PRACTICE;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20),
    DEPARTMENT VARCHAR(10),
    SALARY INT,
    YEAR_EXP int
);


INSERT INTO EMPLOYEES(NAME,DEPARTMENT,SALARY,YEAR_EXP) VALUES
("ALICE","IT",80000,6),
("BOB",'HR',50000,3),
("CHARLIE","IT",65000,4),
("DIANA","FINANCE",90000,8),
("EVAN","HR",45000,2);




SELECT 
	*
FROM EMPLOYEES;

-- CLASSIFY EMPLOYEES BASED ON EXPERIENCE.
-- >=7 -> SENIOR, >=4 -> MID-LEVEL , JUNIOR


SELECT
	*,
    CASE 
		WHEN YEAR_EXP >=7 THEN 'SENIOR'
        WHEN YEAR_EXP >=4 THEN 'MID LEVEL'
        ELSE 'JUNIOR'
	END EXPERINCE_LVL,
    
    CASE 
		WHEN SALARY >= 80000 THEN 'HIGH PAID'
        WHEN SALARY >= 60000 THEN 'MEDIUM PAID'
        ELSE 'LOW'
	END AS SALARY_BAND
FROM EMPLOYEES;


-- CASE WITH WHERE 
SELECT
	*
FROM EMPLOYEES
WHERE 
	CASE 
		WHEN DEPARTMENT ='HR' THEN SALARY >45000
        ELSE SALARY > 60000
	END;
    
-- CASE WITH ORDER BY
SELECT 
	*
FROM EMPLOYEES 
ORDER BY 
	CASE 
		WHEN DEPARTMENT = 'IT' THEN 1
        WHEN DEPARTMENT = 'HR' THEN 2
        WHEN DEPARTMENT = 'FINANCE' THEN 3
	END;
	


-- CONDITIONAL AGGREGATION
-- COUNT HOW MANY EMPLOYEES PER DEPARTMENT EARN >=60000
SELECT 
	DEPARTMENT,
    COUNT(CASE WHEN SALARY>= 60000 THEN 1 END) AS HIGH_EARNERS
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT 
	DEPARTMENT,
    COUNT(SALARY) HIGH_EARNERS
FROM EMPLOYEES
WHERE SALARY >= 60000 -- CHECKING CONDITION ROW WISE , AFTER THAT EVALUATE THE AGGREGATION
GROUP BY DEPARTMENT;



-- VIEWS 
CREATE VIEW EMPLOYEE_VIEW AS 
(	SELECT
		*,
		CASE 
			WHEN YEAR_EXP >=7 THEN 'SENIOR'
			WHEN YEAR_EXP >=4 THEN 'MID LEVEL'
			ELSE 'JUNIOR'
		END EXPERINCE_LVL,
		
		CASE 
			WHEN SALARY >= 80000 THEN 'HIGH PAID'
			WHEN SALARY >= 60000 THEN 'MEDIUM PAID'
			ELSE 'LOW'
		END AS SALARY_BAND
	FROM EMPLOYEES);


SELECT 
	*
FROM EMPLOYEE_VIEW;

-- YOU CAN USE VIEW FOR SECURITY
CREATE VIEW EMP_TABLE AS (
	SELECT 
		EMP_ID,
		NAME,
		DEPARTMENT
	FROM EMPLOYEES);
    
-- DROP THE VIEW
DROP VIEW EMPLOYEE_VIEW;
    
SELECT 
	*
FROM EMP_TABLE;