-- CTE(COMMON TABLE EXPRESSION)
-- IT CREATES A MINI TEMPERORY TABLE FOR THIS QUERY ONLY

-- CTE WORKS TOP TO BOTTOM
-- SUBQUERY WORKS BOTTOM TO TOP



CREATE DATABASE CTECLASS;
USE CTECLASS;
CREATE  TABLE EMPLOYEES(
	EMP_ID INT,
    NAME VARCHAR(20),
    DEPT_ID INT,
    SALARY int
);


CREATE TABLE DEPARTMENT(
	DEPT_ID INT,
    DEPT_NAME VARCHAR(10)
    );
    
    
INSERT INTO EMPLOYEES VALUES(1,'ALICE', 10,60000),(2,'BOB',20,45000),(3,'CAROL',10,75000),(4,'DAVE',30,50000);
INSERT INTO DEPARTMENT VALUES(10,'HR'),(20,'IT'),(30,'FINANCE');



SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENT;


-- EMPLOYEES EARINING MORE THAN 50000
WITH HIGHSALARYEMPLOYEES AS(
	SELECT
		*
	FROM EMPLOYEES
    WHERE SALARY > 50000
)
SELECT NAME, SALARY FROM HIGHSALARYEMPLOYEES;


SELECT
	NAME,
    SALARY
FROM EMPLOYEES 
WHERE EMP_ID IN (SELECT EMP_ID FROM EMPLOYEES WHERE SALARY>50000);


-- EMPLOYEES WITH DEPARTMENT NAMES

WITH EMPLOYEEDETAILS AS(
	SELECT
		E.EMP_ID, 
        E.NAME, 
        D.DEPT_NAME, 
        E.SALARY,
        SUM(SALARY) OVER(PARTITION BY D.DEPT_NAME) SPENDING
        FROM EMPLOYEES E 
        JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID        
)
SELECT * FROM EMPLOYEEDETAILS;



-- MULTIPLE CTE IN QUERY

WITH HIGHSALARYEMPLOYEES AS(
	SELECT
		*
	FROM EMPLOYEES
    WHERE SALARY > 50000
),
DEPTINFO AS (
	SELECT DEPT_ID, DEPT_NAME
    FROM DEPARTMENT
)
SELECT 
	H.NAME, D.DEPT_NAME, H.SALARY 
FROM HIGHSALARYEMPLOYEES H 
JOIN DEPTINFO D 
ON H.DEPT_ID = D.DEPT_ID;


-- CTE WITH GROUP BY / AGGREGATION
WITH AVGSALARY AS (
	SELECT DEPT_ID, AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPT_ID
)
SELECT 
	D.DEPT_NAME, A.AVG_SALARY
FROM AVGSALARY A 
JOIN DEPARTMENT D 
ON A.DEPT_ID = D.DEPT_ID;


-- RECURSIVE CTE (ADVANCED)
CREATE TABLE EMP(
	EMP_ID INT,
    NAME VARCHAR(10),
    MANAGER_ID INT
);


INSERT INTO EMP VALUES
(1,'CEO',NULL),
(2,'DEVMANAGER',1),
(3,'DEVELOPER',2);


WITH RECURSIVE EMPLOYEEHIERARCHY AS (
	SELECT 
		EMP_ID, NAME , MANAGER_ID
    FROM EMP 
    WHERE MANAGER_ID IS NULL
    
    UNION ALL 
    
    SELECT 
		E.EMP_ID , E.NAME, E.MANAGER_ID
	FROM 
		EMP E
	JOIN EMPLOYEEHIERARCHY EH
		ON E.MANAGER_ID = EH.EMP_ID
        
)
SELECT 
	*
FROM EMPLOYEEHIERARCHY;
    


-- REUSABILITY
WITH EMPLOYEEDATA AS (
	SELECT
		EMP_ID, NAME ,DEPT_ID,SALARY
	FROM EMPLOYEES
),
DEPTAVGSALARY AS (
	SELECT DEPT_ID, AVG(SALARY) AS DEPT_AVG_SALARY
	FROM EMPLOYEEDATA
    GROUP BY DEPT_ID
),
COMPANYAVGSALARY AS (
	SELECT 
		AVG(SALARY) AS COMPANY_AVG_SALARY
    FROM EMPLOYEEDATA
)
SELECT 
	D.DEPT_NAME,
    DA.DEPT_AVG_SALARY,
    COUNT(ED.EMP_ID) AS HIGH_PAID_EMPLOYEES
FROM DEPTAVGSALARY DA 
JOIN COMPANYAVGSALARY CA 
	ON DA.DEPT_AVG_SALARY > CA.COMPANY_AVG_SALARY -- FOR WHOLE TABLE
JOIN EMPLOYEEDATA ED
	ON DA.DEPT_ID = ED.DEPT_ID AND ED.SALARY>50000 -- 3 COLUMN 
JOIN DEPARTMENT D 
	ON DA.DEPT_ID = D.DEPT_ID -- THIS IS FOR FIRST COLUMN
GROUP BY D.DEPT_NAME,DA.DEPT_AVG_SALARY;

    

    