-- Subqueries
-- Subquery is a query inside another query.
-- Subquery works bottom to top


-- select column_name
-- from table_name
-- where column_name operator(
-- 	select column_name
-- 	from table_name
--   where condition
-- );


use wedthu1330batch;

CREATE TABLE employee(
	EMP_ID INT,
	EMP_NAME VARCHAR(50),
	DEPARTMENT VARCHAR(50),
	SALARY INT,
	MANAGER_ID  INT
);



INSERT INTO  EMPLOYEE VALUES
(1,'AMIT','IT',60000,3),
(2,'NEHA','HR',45000,3),
(3,'ROHIT','IT',80000,NULL),
(4,'PRIYA','FINANCE',70000,5),
(5,'ANKIT','FINANCE',90000,NULL),
(6,'SNEHA','IT',50000,3);



-- SINGLE ROW SUBQUERY(IT RETURNS ME SINGLE ROW)
-- EMPLOYEE WITH HIGHEST SALARY
SELECT 
	EMP_NAME,
    SALARY
FROM EMPLOYEE
WHERE SALARY = 
		(SELECT 
			MAX(SALARY) 
		FROM EMPLOYEE);


-- EMPLOYEES EARNING MORE THAN AVERAGE SALARY

SELECT 
	EMP_NAME,
    SALARY
FROM EMPLOYEE
WHERE SALARY > 
		(SELECT 
			AVG(SALARY) 
		FROM EMPLOYEE);




-- EMPLOYEES FROM DEPARTMENT THOSE HAVE MANAGERS

SELECT 
	EMP_NAME
FROM EMPLOYEE WHERE DEPARTMENT NOT IN
(SELECT 
	DEPARTMENT 
FROM 
EMPLOYEE WHERE MANAGER_ID IS NULL);

-- EMPLOYEES THOSE ARE EARNING MORE THAN ANY IT EMPLOYEE

SELECT
	EMP_NAME,
    DEPARTMENT,
    SALARY
FROM EMPLOYEE
WHERE SALARY > ANY(
	SELECT
		SALARY 
	FROM EMPLOYEE
	WHERE DEPARTMENT = 'IT') AND DEPARTMENT != 'IT';


-- EMPLOYEE EARNING MORE THAN ALL IT EMPLOYEES
SELECT
	EMP_NAME,
    DEPARTMENT,
    SALARY
FROM EMPLOYEE
WHERE SALARY > ALL(
	SELECT
		SALARY 
	FROM EMPLOYEE
	WHERE DEPARTMENT = 'IT') AND DEPARTMENT != 'IT';

-- FIND HIGHEST PAID EMPLOYEE IN EACH DEPARTMENT
SELECT
	EMP_NAME,
    DEPARTMENT,
    SALARY
FROM EMPLOYEE
WHERE (DEPARTMENT,SALARY) IN
	(SELECT
		DEPARTMENT,
		MAX(SALARY)
	FROM EMPLOYEE 
	GROUP BY DEPARTMENT);
    
-- CORRELATED SUBQUERY
-- EMPLOYEES EARNING MORE THAN DEPARTMENT AVERAGE
SELECT
	EMP_NAME,
    SALARY,
    DEPARTMENT
FROM EMPLOYEE E1
WHERE SALARY > (
	SELECT 
		AVG(SALARY)
	FROM EMPLOYEE E2
    WHERE  E1.DEPARTMENT= E2.DEPARTMENT
);




-- SUBQUERY INSIDE SELECT CLAUSE
-- SHOW EMPLOYEE ALONG WITH AVERAGE SALARY OF THE DEPARTMENT
SELECT
	EMP_NAME,
    (
		SELECT 
			AVG(SALARY) FROM EMPLOYEE E2
        WHERE E1.DEPARTMENT = E2.DEPARTMENT
    ) AS DEPT_AVG_SALARY
FROM EMPLOYEE E1;




-- QUERY INSIDE FROM CLAUSE
SELECT
	T.DEPARTMENT,
    T.SPENDING
FROM(
	SELECT 
		DEPARTMENT,
		SUM(SALARY) AS SPENDING
	FROM EMPLOYEE 
	GROUP BY DEPARTMENT
) AS T
WHERE T.SPENDING > 100000;